### ISSUE TITLE
Continuation of the issues about Aeva doppler velocities 

### ISSUE THREAD

**Issue by kahowang** [minwoo0611/helipr_file_player#4]
Hi minwoo,

Continuation of the issues about Aeva doppler velocities : [https://github.com/minwoo0611/Awesome-3D-LiDAR-Datasets/issues/5]( https://github.com/minwoo0611/Awesome-3D-LiDAR-Datasets/issues/5)

1. As you mentioned, the velocities in the dataset is absolute velocities. Would you like to ask, is the absolute velocities of the pointcloud directly obtained by the sensor or estimated by you through your own algorithm?

2. At the same time, as far as I know, FMCW LiDAR can feedback direct raw relative Doppler velocity, may I ask if you have a backup of the original data (like radial velocity of pointcloud)?

3.  What is the approximate vechile velocity in different datasets? (For example, in the `Bridge02` dataset, vechile's velocity when moving on the bridge)

Looking forward for your reply~
Kaho

**Comment by minwoo0611** [comment]
Thank you for your continued interest and questions regarding the Aeva LiDAR velocities in the HeLiPR Dataset.

1. The absolute velocities in the dataset are directly obtained by the sensor. The exact method for deriving absolute velocity is not detailed, but it's plausible that the sensor combines radial velocity with the vehicle's body velocity, obtained from an Inertial Measurement Unit (IMU), to calculate this. There are two modes for publishing the velocity (absolute vs relative)

2. Regarding the backup of original data, like the radial velocity of the point cloud, it's challenging to provide this as it depends on how the LiDAR sensor and data processing pipeline are configured. The approximate relative velocity can be calculated by adding the body velocity from INS, but it may not be accurate.

3. To determine the approximate vehicle velocity in different datasets, such as in the Bridge02 dataset, you can refer to the 'inertial_data/inspva.csv' file. This file contains Inertial Navigation System (INS) data, including north velocity, east velocity, and up velocity, which can help you approximate the vehicle's motion. The data is organized as follows: [timestamp, latitude, longitude, height, north velocity, east velocity, up velocity, roll, pitch, azimuth, status] and is sampled at a frequency of 50Hz.

I hope this information is helpful to your research. For more detailed or specific inquiries, I recommend reaching out directly within the specific dataset's repository.

Best regards,
Minwoo

**Comment by kahowang** [comment]
Hi minwoo,

Thank you for your great help!!!

kaho
